# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b368997e4fc21ec4390a8bfeebb8874a8e25561d9b7efff307f014bb992f89b6a03a736525c9c6c3555c1cbe93e3287b257c772c45adb053cab4134fdd836807

test:
  secret_key_base: f7a3c23c935b2695fa527ecdb2b8215fddb39c0c4ae7f100bbf9c8fee0b41c8078cae3cd8b28caac0afe6b6fcf5a0428d5217cfb49387f19f5ac7bc5123156c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
